Add downloading of configuration-defined projects
zyedidia/eget pull request #62
Opened 2022-11-20 11:06 UTC by patinthehat

## Overview
This PR adds an additional flag, `-D`/`--download-config`, which adds new functionality:

When specifying the `--download-config` flag, all projects/repositories defined in the configuration file are downloaded in the order they exist within the config file.

If this flag is specified, no other parameters are required.

## Implementation

This functionality was implemented by using `exec.Command()` to execute the currently running binary (which is an `eget` binary) sequentially for each of the configuration-defined repositories, and the output from the process is streamed in real time to the current `stdout` pipe using a scanner created by `bufio.NewScanner()` for reading the output.

This allows a complete implementation of batch downloading with a minimal amount of additional code, as it leverages `eget` functionality itself.

## Example Usage

Given the following configuration file:

```toml
[global]
    github_token = ""
    quiet = false
    show_hash = true
    upgrade_only = true
    target = "./test"

["zyedidia/micro"]
    name = "micro"
    upgrade_only = false
    show_hash = false
    asset_filters = [ "static.tar.gz" ]

["zyedidia/eget"]
    name = "eget"
    upgrade_only = false
    show_hash = false
    asset_filters = [ ".tar.gz" ]

["junegunn/fzf"]
    name = "fzf"
    upgrade_only = false
    quiet = false
```

The following output is displayed when running `eget --download-config`:
![image](https://user-images.githubusercontent.com/5508707/202898352-db09aa2b-b8d4-47ba-9900-f9a2de5c851f.png)

### Notes

I'm not 100% sure that `--download-config` is the best name for this flag, so please suggest alternatives if anything comes to mind.  I feel that it could be confusing if an end user thinks that the flag means a configuration file will be downloaded.

Alternatives could be `--batch-download`, `--download-configured`, or something similar. Thoughts?

2022-11-24 03:59 UTC, zyedidia commented
Cool thanks! I left some comments, and I think we should change the flag name to `--download-all`.

2022-11-24 13:12 UTC, patinthehat commented
@zyedidia I've updated the flag name, which is much better than the original choice, thanks for the suggestion.  Could you please re-review?

2022-11-25 06:01 UTC, zyedidia requested changes

2022-11-25 06:03 UTC, zyedidia commented
Thanks, I think there are still some changes to be made (see the review comments), and then I'll merge.

2022-11-26 00:38 UTC, patinthehat commented on eget.go
> +		cmd := exec.Command(os.Args[0], name)
Good call, I'll change that :+1:

2022-11-26 00:42 UTC, patinthehat commented on eget.go
> +		}
Thanks, that's a much better implementation!

2022-11-26 00:44 UTC, patinthehat commented on eget.go
> +		}
Thanks for the pointers, I'm definitely getting better with golang :+1:

2022-11-26 00:51 UTC, patinthehat commented on eget.go
> +		return errors.New("one or more repositories failed to download")
Good call, I was thinking of changing this to do just that anyway.

2022-11-26 00:54 UTC, patinthehat commented
@zyedidia I've addressed all of the change requests - would you please re-review at your convenience? Thanks for all of the great suggestions to improve the code. :+1:

2022-11-26 01:31 UTC, zyedidia commented
Looks good, thanks!

2022-11-26 01:31 UTC, zyedidia approved these changes

2022-11-26 01:32 UTC, merged